### ISSUE TITLE
Fix for IE6 support

### ISSUE THREAD

**Issue by eltonjude** [ternarylabs/porthole#18]
If inside the dispatchMessage function (legacy mode) you change the width of  this.proxyIFrameElement rather than its height, the resize event will fire and things will work.

Hint: http://www.velocityreviews.com/forums/t642052-iframe-resize-events.html

Also, users should include https://github.com/douglascrockford/JSON-js/blob/master/json2.js in their code to make JSON available.

**Comment by georges** [comment]
Hopefully IE6 is no longer a concern
