### ISSUE TITLE
Do a windowProxy.post when the page loads

### ISSUE THREAD

**Issue by juanbzz** [ternarylabs/porthole#22]
I'm trying to get data from localStorage and send it to the guest when the page loads but it doesn't works, any workaround or solution?

```
(function($){
  windowProxy.post({'html' : localStorage.getItem('htmlDB') });
})(jQuery);
```

issue more detailed [here](http://forrst.com/posts/jQuery_CrossDomain_comunication_issue_with_Por-HcQ)

**Comment by GaboTaneco** [comment]
I have the same problem. I call windowProxy.post inside a success ajax, this ajax submit my form.
windowProxy.Post work in chrome, but don't work in safari.
