### ISSUE TITLE
Fork a New & Maintained Project

### ISSUE THREAD

**Issue by zmonteca** [ternarylabs/porthole#29]
Somebody else needs to take control of this project and/or fork and actually maintain it. There are a ton of pull requests that are completely legitimate and very useful that have not been merged. It's very frustrating.

**Comment by georges** [comment]
Thanks for taking over merging those PRs. I've merged your fork. As far as changes, mostly dealing with using IE8 native ability to send messages, which seemed to fix a problem for newer browser using IE8 compatibility mode.
