### ISSUE TITLE
why specify url when creating Porthole.windowProxy? Seems to do fine without

### ISSUE THREAD

**Issue by gebrits** [ternarylabs/porthole#31]
When rendering an Iframe as per the docs I need to pass the url of the parent window as so: 
`windowProxy = new Porthole.WindowProxy( 'http://other-domain.com/proxy.html');`

However, bc. of limitations of my server setup it's kind of a hack to get the variable url of the parent window on the server. 

Therefore, I tried doing the following which just seems to work: 
`windowProxy = new Porthole.WindowProxy();`

So, what would be the reason for having to pass the url of the parent window if any?

**Comment by georges** [comment]
That's probably because the browser supports native message passing and only needs a reference to the window object. Older browser, the communication was done via fragments on iframe url.
