### ISSUE TITLE
Not working on IE8!

### ISSUE THREAD

**Issue by cgrimal** [ternarylabs/porthole#32]
Hi Guys,

I have spent the last hours trying to understand why my code that is using Porthole wasn't working on the website of a client and found out they were forcing IE8 compatibility mode. I checked and Porthole is supposed to be working on IE8 but it is quite straightforward to check for yourself that it's not: 

Go to http://sandbox.ternarylabs.com/porthole/ with IE, and set the compatibility mode to IE8 (window.postMessage shouldn't be defined, Porthole is switching to legacy mode) and the demo does not work!

Any idea why? Do you know any workaround?

Thanks,
Clément

**Comment by georges** [comment]
Indeed compatibility mode was causing problem. Updated the code with many changes that address this.
