### ISSUE TITLE
Iframe inside an Iframe

### ISSUE THREAD

**Issue by janstadt** [ternarylabs/porthole#33]
We have an application in which our clients launch our container app into an iframe. This iframe (call it the 'orchestrator') then can launch a number of applications within it via another iframe (call it a 'product'). At the moment, it seems that `getTargetWindow` is having an issue with my setup.

What we want to do is set up a communication proxy between product iframe and orchestrator iframe. At the moment, i have unilateral communication from product to orchestrator, but i cant seem to get orchestrator to product figured out.

Product Iframe talking to orchestrator (works):

```
var proxy = Porthole.WindowProxy('orchestratordomain/proxy.html`, 'parent');
proxy.post(message);
```

Orchestrator Iframe talking to product (doesnt):

```
var proxy = Porthole.WindowProxy('productdomain/proxy.html`, 'productFrameName');
proxy.post(message);
```

![DOM Layout](http://content.screencast.com/users/janstadt/folders/Jing/media/b21e5765-da42-4558-9866-c112e8da34b7/2015-01-20_1456.png)

When we get to `getTargetWindow` on line 384 for the scenario that doesnt work is `targetWindowName` thats being sent in is `productFrameName` that we do a `parent.frames['productFrameName'];` which is null since the parent.frames is essentially pointing to the `http://clientapp.com` location which doesnt have the productFrameName in it. 

I updated the else if on line 381 to do `|| window[targetWindowName]` which for my scenario DOES find 'productFrameName' but when i try and post a message to it, my event handlers are not firing.

So there could really be two different things going on here:
- Porthole doesnt support iFrame communication inside of an iFrame
- My event handlers are jacked up

Whats weird is that it works from the product up to the orchestrator, but not from the orchestrator down. Im fairly new to how porthole works but would love some help if at all possible. 

Here is a link to my public dropbox that essentially lays out what im talking about. I added this to a webserver and it failed on the same place its failing on it for me.
https://www.dropbox.com/s/0lu4y01zsbegbjx/test.html?dl=0

Any help would be greatly appreciated, especially if this is not a viable solution for our application as we are currently in the prototyping phase.

Thanks,

Jake

**Comment by ghost** [comment]
@janstadt Did you have any luck with this?

**Comment by janstadt** [comment]
@kobell i ended up ditching porthole and instead used https://github.com/secondstreet/talker.js/tree/master
I cant really recommend talker.js either to be honest and if i had to do it all over again, i would have just created my own postmessage wrapper.
