### ISSUE TITLE
No git tags on GitHub repository

### ISSUE THREAD

**Issue by dakshshah96** [ternarylabs/porthole#48]
Hey @georges,

I'd like to host your library, porthole on [cdnjs](https://github.com/cdnjs/cdnjs) — It is one of the most famous free and public web front-end CDN services which is used by [~1,143,000 websites](https://trends.builtwith.com/cdn/CDN-JS) worldwide.

The git auto-updater for cdnjs relies on [git tags](https://github.com/moappi/json2html/tags) to recognize a release version and automatically update the library in the cdnjs repo.

If it's not too much to ask, can you please add git tags for this repo?

[cdnjs/cdnjs/11143](https://github.com/cdnjs/cdnjs/issues/10486)

**Comment by georges** [comment]
Done, v1.0.0 tag added

**Comment by dakshshah96** [comment]
Thanks @georges 😄
