### ISSUE TITLE
IE8 caused error: "Porthole: Could not find window proxy object on the target window" while FF works fine

### ISSUE THREAD

**Issue by leszekgruchala** [ternarylabs/porthole#7]
Hi,
I know the demo is working fine on IE7/8, but I am completely unable to make it working with IE8 on my application.
It works fine on Chrome, FF and IE9, but not on IE8.

My parent and iframe uses SSL.

This is what I get on IE9 with IE8 compatibility mode:

```
LOG: Porthole: Using legacy browser support 
Porthole: Could not find window proxy object on the target window 
```

but it still works well on IE9 and other normal browsers with the same code.

Unfortunately I know JS just a bit, but I google and found an idea to wrap postMessage call in setTimeout:

```
var func = function () {
        windowProxy.postMessage('sid=B099000003&msisdn=48791464671');
};
window.setTimeout(func, 0);
```

But it doesn't help. Another strange this is that for pure IE8 I even don't get any LOG message from Porthole on console.

Do you have any idea what might cause the problem? Or anything I could do to help you find it?
Thanks.

**Comment by baileyjames9** [comment]
@zmonteca Thanks for the fork and response. Works great on IE8. 

I do wish as developers we were always in a position to dictate to clients using our software what browser to use, but alas, some of us are not. There are big money contracts involved and large corporations are slow to migrate in certain industries.

**Comment by jrodri2001** [comment]
I had this problem today when having IE9 running in IE8 mode. same for IE9 running in IE8 mode. What worked for me was to comment out line 463 of porthole.js:
```javascript
if (w[i] !== null &&
    typeof w[i] === 'object' &&
    //w[i] instanceof w.Porthole.WindowProxy &&
    w[i].getTargetWindowName() === sourceWindowName) {
    return w[i];
}
```

for some reason w.Porthole.WindowProxy is not the an instance of w[i] when forcing IE8 mode, although it does work on IE8 directly.

Hope it helps someone.

**Comment by georges** [comment]
Native IE8 browser seemed to work fine. There was a problem with newer IE browser running in IE8 compatibility mode. I've merge many changes contributed over the last year to address this kind of problems. Master is up to date now. Did a quick sanity check on IE8-IE11 and demo code works fine.
